from pathlib import Path


SHARED_PRIME = 12969878687210734169725370852702107963291791205879981534969246073051690806981060949573821700986993519709785477293123384307472011966540705954444091494986193
Q_A = 8931771124747275863742092320363425563220697265307205924322793693052235402089507816450059993648439125775595994051102726070844739506797575158420943847254851
Q_B = 8496621203671386303918918598064255187826114607142805312291415533111176415127581852711028938772590066787281385933222153601961221953431088645392336999350791
E = 65537
PLAINTEXT = "RSA AUDIT COMPLETE\nFlag: sentctf{gcd_br34k5_r3u53d_r54}"


def main():
    n_a = SHARED_PRIME * Q_A
    n_b = SHARED_PRIME * Q_B
    message = int.from_bytes(PLAINTEXT.encode(), "big")
    if message >= n_b:
        raise ValueError("Plaintext is too large for the target RSA modulus")

    ciphertext = pow(message, E, n_b)
    output = (
        "RSA KEY AUDIT\n\n"
        "The following public keys were generated by the same service.\n"
        "The protected message was encrypted for key_b.\n\n"
        f"e = {E}\n"
        f"n_a = {n_a}\n"
        f"n_b = {n_b}\n"
        f"c = {ciphertext}\n"
    )

    destination = Path(__file__).resolve().parents[1] / "dist" / "captured_keys.txt"
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(output, encoding="ascii")


if __name__ == "__main__":
    main()
